import type { Locale } from '../hooks/useLocale';

export const wording = {
  en: {
    vaccinations: {
      title: 'Vaccinations',
      needsAttention: 'Needs\nAttention',
      needsAttentionBody: "Let's ensure your pet\nstays fully protected and\nhealthy.",
      oneOverdue: '1 Overdue',
      oneDueSoon: '1 Due soon',
      resolve: 'Resolve',
      nextUp: 'NEXT UP',
      vaccineHistory: 'VACCINE HISTORY',
      dueDate: 'Due Date',
      addVaccination: 'Add Vaccination',
      statuses: {
        overdue: 'Overdue',
        dueSoon: 'Due soon',
        upToDate: 'Up to date',
      },
      nextCard: {
        name: 'Rabies',
        subtitle: '1-year vaccine',
        date: 'Apr 12',
        inWeeks: 'in 3 weeks',
      },
      history: {
        bordetellaSub: 'Kennel Cough',
        rabiesSub: '1-year vaccine',
        dhppSub: 'Distemper, Parvo, etc.',
        leptoSub: 'Bacterial infection',
        bordetellaDate: 'Feb 20, 2026',
        rabiesDate: 'Apr 12, 2026',
        dhppDate: 'Jan 15, 2027',
        leptoDate: 'Mar 10, 2027',
      },
    },
    vetVisits: {
      title: 'Vet Visits',
      medicalHistory: 'Medical History',
      visitsCount: '3 Visits',
      totalCost: '$265 Total',
      addVisit: 'Add Visit',
      addPayment: 'Add\npayment',
      attachDocuments: '+ Attach documents or photos',
      visits: {
        v1Date: 'Mar 5, 2026',
        v1Title: 'Annual Checkup\n& Vaccines',
        v1Clinic: 'Downtown Vet Clinic',
        v1Doctor: 'Dr. Sarah Jenkins',
        v2Date: 'Oct 12, 2025',
        v2Title: 'Ear Infection Follow-up',
        v2Clinic: 'Downtown Vet Clinic',
        v2Doctor: 'Dr. Sarah Jenkins',
        v3Date: 'Mar 10, 2025',
        v3Title: 'Annual Checkup',
        v3Clinic: 'City Pet Hospital',
        v3Doctor: 'Dr. Emily Chen',
      },
    },
    healthRecords: {
      title: 'Health Records',
      overview: 'Health Overview',
      recordsCount: '6 Records',
      activeCount: '2 Active',
      upToDate: 'Up to date',
      allergies: 'Allergies',
      diagnoses: 'Diagnoses',
      labResults: 'Lab Results',
      activeSection: 'ACTIVE',
      historySection: 'HISTORY',
      activeTitle: 'Chicken Protein',
      activeDate: 'Oct 12, 2025',
      activeBody: 'Severe itching and paw biting\nwhen consumed.',
      activeBadge: 'Active',
      activeSeverity: 'High',
      historyTitle: 'Flea Bites',
      historyDate: 'Jun 05, 2024',
      historyBody: 'Treated with seasonal preventative.',
      resolvedBadge: 'Resolved',
      historySeverity: 'Medium',
      addRecord: 'Add Record',
    },
    weightTracking: {
      title: 'Weight Profile',
      subtitle: 'Weight profile',
      currentWeight: 'CURRENT WEIGHT',
      healthyReferencePrefix: 'Healthy reference',
      last90Days: 'Last 90 Days',
      smartInsights: 'Smart Insights',
      history: 'History',
      addEntry: 'Add entry',
      addWeightEntry: 'Add Weight Entry',
      weightPlaceholder: 'e.g. 5.3',
      enterValidWeight: 'Enter a valid weight in kg.',
      save: 'Save',
      current: 'Current',
      currentSuffix: 'vs current',
      withinHealthyRange: 'Within healthy range',
      belowHealthyRange: 'Below healthy range',
      aboveHealthyRange: 'Above healthy range',
      trendInRange: "{name}'s trend is currently aligned with the expected {target} range.",
      trendBelow: '{name} is tracking below the expected {target} range. A nutrition review can help.',
      trendAbove: '{name} is tracking above the expected {target} range. Portion and activity review is recommended.',
      referenceAwareTitle: 'Reference-aware trend',
      referenceAwareBody: 'Curve movement now compares directly against the healthy range band.',
      noDate: 'No date',
      petFallback: 'pet',
      todayFallback: 'Today',
      stableFallback: 'Stable',
      refs: {
        catBritish: 'Healthy range for British Shorthair is usually 3.2-7.7 kg.',
        catMaine: 'Healthy range for Maine Coon is usually 4.5-8.2 kg.',
        catRagdoll: 'Healthy range for Ragdoll is usually 3.6-9.0 kg.',
        catSiamese: 'Healthy range for Siamese is usually 2.5-5.5 kg.',
        catDefault: 'Typical healthy range for adult cats is usually 3.0-6.0 kg.',
        dogGolden: 'Healthy range for Golden Retriever is usually 25-34 kg.',
        dogLabrador: 'Healthy range for Labrador is usually 25-36 kg.',
        dogGerman: 'Healthy range for German Shepherd is usually 22-40 kg.',
        dogKangal: 'Healthy range for Kangal is usually 40-65 kg.',
        dogTerrier: 'Expected healthy Terrier range can vary by subtype, often around 6-12 kg.',
        dogDefault: 'General adult dog healthy range varies by breed; using a 10-30 kg reference for this profile.',
        default: 'A general reference range is used for this profile.',
      },
    },
    premium: {
      badge: 'V-Paw Premium',
      heading: 'Give your pet the\ncare they deserve',
      subheading: "Unlock the ultimate toolkit to manage\nyour pet's health, records, and daily life\nwith ease.",
      features: {
        unlimitedPetsTitle: 'Unlimited Pets',
        unlimitedPetsDesc: 'Add as many furry friends as you want.',
        fullHealthTitle: 'Full Health History',
        fullHealthDesc: 'Lifetime access to all medical records.',
        pdfPassportTitle: 'PDF Health Card',
        pdfPassportDesc: "Export your pet's complete health summary as a PDF.",
        aiTitle: 'Smart Health Insights',
        aiDesc: "Automatic analysis of your pet's health data.",
        remindersTitle: 'Smart Reminders',
        remindersDesc: 'Never miss a vaccination or pill again.',
      },
      table: {
        free: 'FREE',
        pro: 'PRO',
        petProfiles: 'Pet Profiles',
        healthRecords: 'Health Records',
        pdfExport: 'PDF Export',
        aiInsights: 'Smart Insights',
        one: '1',
        unlimited: 'Unlimited',
        threeMonths: '3 months',
        lifetime: 'Lifetime',
      },
      upgrade: 'Upgrade for $4.99/mo',
      maybeLater: 'Maybe later',
    },
    profileEdit: {
      title: 'Edit Profile',
      nameLabel: 'Full Name',
      namePlaceholder: 'Full Name',
      avatarLabel: 'Avatar URL',
      avatarPlaceholder: 'https://...',
      save: 'Save',
      saving: 'Saving...',
      saveFailedTitle: 'Save failed',
      saveFailedBody: 'Profile could not be saved. Please try again.',
    },
  },
  tr: {
    vaccinations: {
      title: 'Aşılar',
      needsAttention: 'Dikkat\nGerekiyor',
      needsAttentionBody: 'Hayvanınızın tam korumada\nolduğundan ve sağlıklı\nkaldığından emin olalım.',
      oneOverdue: '1 Gecikmiş',
      oneDueSoon: '1 Yaklaşıyor',
      resolve: 'Çöz',
      nextUp: 'SIRADAKİ',
      vaccineHistory: 'AŞI GEÇMİŞİ',
      dueDate: 'Son Tarih',
      addVaccination: 'Aşı Ekle',
      statuses: {
        overdue: 'Gecikmiş',
        dueSoon: 'Yaklaşıyor',
        upToDate: 'Güncel',
      },
      nextCard: {
        name: 'Kuduz',
        subtitle: '1 yıllık aşı',
        date: '12 Nis',
        inWeeks: '3 hafta sonra',
      },
      history: {
        bordetellaSub: 'Kennel Öksürüğü',
        rabiesSub: '1 yıllık aşı',
        dhppSub: 'Distemper, Parvo vb.',
        leptoSub: 'Bakteriyel enfeksiyon',
        bordetellaDate: '20 Şub 2026',
        rabiesDate: '12 Nis 2026',
        dhppDate: '15 Oca 2027',
        leptoDate: '10 Mar 2027',
      },
    },
    vetVisits: {
      title: 'Veteriner Ziyaretleri',
      medicalHistory: 'Tıbbi Geçmiş',
      visitsCount: '3 Ziyaret',
      totalCost: '$265 Toplam',
      addVisit: 'Ziyaret Ekle',
      addPayment: 'Ödeme\nekle',
      attachDocuments: '+ Belge veya fotoğraf ekle',
      visits: {
        v1Date: '5 Mar 2026',
        v1Title: 'Yıllık Kontrol\nve Aşılar',
        v1Clinic: 'Downtown Vet Clinic',
        v1Doctor: 'Dr. Sarah Jenkins',
        v2Date: '12 Eki 2025',
        v2Title: 'Kulak Enfeksiyonu Kontrolü',
        v2Clinic: 'Downtown Vet Clinic',
        v2Doctor: 'Dr. Sarah Jenkins',
        v3Date: '10 Mar 2025',
        v3Title: 'Yıllık Kontrol',
        v3Clinic: 'City Pet Hospital',
        v3Doctor: 'Dr. Emily Chen',
      },
    },
    healthRecords: {
      title: 'Sağlık Kayıtları',
      overview: 'Sağlık Özeti',
      recordsCount: '6 Kayıt',
      activeCount: '2 Aktif',
      upToDate: 'Güncel',
      allergies: 'Alerjiler',
      diagnoses: 'Tanılar',
      labResults: 'Lab Sonuçları',
      activeSection: 'AKTİF',
      historySection: 'GEÇMİŞ',
      activeTitle: 'Tavuk Proteini',
      activeDate: '12 Eki 2025',
      activeBody: 'Tüketildiğinde şiddetli kaşıntı\nve pati ısırma görülür.',
      activeBadge: 'Aktif',
      activeSeverity: 'Yüksek',
      historyTitle: 'Pire Isırıkları',
      historyDate: '05 Haz 2024',
      historyBody: 'Mevsimsel koruyucu ile tedavi edildi.',
      resolvedBadge: 'Çözüldü',
      historySeverity: 'Orta',
      addRecord: 'Kayıt Ekle',
    },
    weightTracking: {
      title: 'Kilo Profili',
      subtitle: 'Kilo profili',
      currentWeight: 'GÜNCEL KİLO',
      healthyReferencePrefix: 'Sağlıklı referans',
      last90Days: 'Son 90 Gün',
      smartInsights: 'Akıllı İçgörüler',
      history: 'Geçmiş',
      addEntry: 'Kayıt ekle',
      addWeightEntry: 'Kilo Kaydı Ekle',
      weightPlaceholder: 'örn. 5,3',
      enterValidWeight: 'Lütfen kg cinsinden geçerli bir değer girin.',
      save: 'Kaydet',
      current: 'Güncel',
      currentSuffix: 'güncele göre',
      withinHealthyRange: 'Sağlıklı aralıkta',
      belowHealthyRange: 'Sağlıklı aralığın altında',
      aboveHealthyRange: 'Sağlıklı aralığın üstünde',
      trendInRange: '{name} için eğilim şu an beklenen {target} aralığıyla uyumlu.',
      trendBelow: '{name}, beklenen {target} aralığının altında seyrediyor. Beslenme değerlendirmesi yardımcı olabilir.',
      trendAbove: '{name}, beklenen {target} aralığının üstünde seyrediyor. Porsiyon ve aktivite düzeni önerilir.',
      referenceAwareTitle: 'Referans uyumlu eğilim',
      referenceAwareBody: 'Eğri hareketi artık sağlıklı aralık bandıyla doğrudan karşılaştırılır.',
      noDate: 'Tarih yok',
      petFallback: 'hayvan',
      todayFallback: 'Bugün',
      stableFallback: 'Stabil',
      refs: {
        catBritish: 'British Shorthair için sağlıklı aralık genelde 3.2-7.7 kg.',
        catMaine: 'Maine Coon için sağlıklı aralık genelde 4.5-8.2 kg.',
        catRagdoll: 'Ragdoll için sağlıklı aralık genelde 3.6-9.0 kg.',
        catSiamese: 'Siamese için sağlıklı aralık genelde 2.5-5.5 kg.',
        catDefault: 'Yetişkin kedilerde sağlıklı aralık çoğunlukla 3.0-6.0 kg arasındadır.',
        dogGolden: 'Golden Retriever için sağlıklı aralık genelde 25-34 kg.',
        dogLabrador: 'Labrador için sağlıklı aralık genelde 25-36 kg.',
        dogGerman: 'German Shepherd için sağlıklı aralık genelde 22-40 kg.',
        dogKangal: 'Kangal için sağlıklı aralık genelde 40-65 kg.',
        dogTerrier: 'Sağlıklı Terrier aralığı alt tipe göre değişebilir, genelde 6-12 kg bandındadır.',
        dogDefault: 'Yetişkin köpeklerde sağlıklı aralık ırka göre değişir; bu profil için 10-30 kg referansı kullanılıyor.',
        default: 'Bu profil için genel bir referans aralığı kullanılıyor.',
      },
    },
    premium: {
      badge: 'V-Paw Premium',
      heading: 'Hayvanınıza hak ettiği\nbakımı sunun',
      subheading: 'Hayvanınızın sağlık, kayıt ve günlük\nyaşam yönetimi için tüm özellikleri\ntek yerde açın.',
      features: {
        unlimitedPetsTitle: 'Sınırsız Hayvan',
        unlimitedPetsDesc: 'Dilediğiniz kadar dost ekleyin.',
        fullHealthTitle: 'Tam Sağlık Geçmişi',
        fullHealthDesc: 'Tüm tıbbi kayıtlara ömür boyu erişim.',
        pdfPassportTitle: 'PDF Sağlık Kartı',
        pdfPassportDesc: 'Hayvanınızın sağlık özetini PDF olarak dışa aktarın.',
        aiTitle: 'Akıllı Sağlık İçgörüleri',
        aiDesc: 'Hayvanınızın sağlık verilerinin otomatik analizi.',
        remindersTitle: 'Akıllı Hatırlatmalar',
        remindersDesc: 'Aşı veya ilaç takibini kaçırmayın.',
      },
      table: {
        free: 'ÜCRETSİZ',
        pro: 'PRO',
        petProfiles: 'Hayvan Profilleri',
        healthRecords: 'Sağlık Kayıtları',
        pdfExport: 'PDF Dışa Aktarım',
        aiInsights: 'Akıllı İçgörüler',
        one: '1',
        unlimited: 'Sınırsız',
        threeMonths: '3 ay',
        lifetime: 'Ömür boyu',
      },
      upgrade: 'Aylık $4.99 ile yükselt',
      maybeLater: 'Daha sonra',
    },
    profileEdit: {
      title: 'Profili Düzenle',
      nameLabel: 'Ad Soyad',
      namePlaceholder: 'Ad Soyad',
      avatarLabel: 'Avatar URL',
      avatarPlaceholder: 'https://...',
      save: 'Kaydet',
      saving: 'Kaydediliyor...',
      saveFailedTitle: 'Kaydetme başarısız',
      saveFailedBody: 'Profil kaydedilemedi. Lütfen tekrar deneyin.',
    },
  },
} as const;

export function getWording(locale: Locale) {
  return wording[locale] ?? wording.en;
}
