import type { Locale } from '../hooks/useLocale';

export const wording = {
  en: {
    vaccinations: {
      title: 'Vaccinations',
      needsAttention: 'Needs\nAttention',
      needsAttentionBody: "Let's ensure your pet\nstays fully protected and\nhealthy.",
      oneOverdue: '1 Overdue',
      oneDueSoon: '1 Due soon',
      resolve: 'Resolve',
      nextUp: 'NEXT UP',
      vaccineHistory: 'VACCINE HISTORY',
      dueDate: 'Due Date',
      addVaccination: 'Add Vaccination',
      statuses: {
        overdue: 'Overdue',
        dueSoon: 'Due soon',
        upToDate: 'Up to date',
      },
      nextCard: {
        name: 'Rabies',
        subtitle: '1-year vaccine',
        date: 'Apr 12',
        inWeeks: 'in 3 weeks',
      },
      history: {
        bordetellaSub: 'Kennel Cough',
        rabiesSub: '1-year vaccine',
        dhppSub: 'Distemper, Parvo, etc.',
        leptoSub: 'Bacterial infection',
        bordetellaDate: 'Feb 20, 2026',
        rabiesDate: 'Apr 12, 2026',
        dhppDate: 'Jan 15, 2027',
        leptoDate: 'Mar 10, 2027',
      },
    },
    vetVisits: {
      title: 'Vet Visits',
      medicalHistory: 'Medical History',
      visitsCount: '3 Visits',
      totalCost: '$265 Total',
      addVisit: 'Add Visit',
      addPayment: 'Add\npayment',
      attachDocuments: '+ Attach documents or photos',
      visits: {
        v1Date: 'Mar 5, 2026',
        v1Title: 'Annual Checkup\n& Vaccines',
        v1Clinic: 'Downtown Vet Clinic',
        v1Doctor: 'Dr. Sarah Jenkins',
        v2Date: 'Oct 12, 2025',
        v2Title: 'Ear Infection Follow-up',
        v2Clinic: 'Downtown Vet Clinic',
        v2Doctor: 'Dr. Sarah Jenkins',
        v3Date: 'Mar 10, 2025',
        v3Title: 'Annual Checkup',
        v3Clinic: 'City Pet Hospital',
        v3Doctor: 'Dr. Emily Chen',
      },
    },
    healthRecords: {
      title: 'Health Records',
      overview: 'Health Overview',
      recordsCount: '6 Records',
      activeCount: '2 Active',
      upToDate: 'Up to date',
      allergies: 'Allergies',
      diagnoses: 'Diagnoses',
      labResults: 'Lab Results',
      activeSection: 'ACTIVE',
      historySection: 'HISTORY',
      activeTitle: 'Chicken Protein',
      activeDate: 'Oct 12, 2025',
      activeBody: 'Severe itching and paw biting\nwhen consumed.',
      activeBadge: 'Active',
      activeSeverity: 'High',
      historyTitle: 'Flea Bites',
      historyDate: 'Jun 05, 2024',
      historyBody: 'Treated with seasonal preventative.',
      resolvedBadge: 'Resolved',
      historySeverity: 'Medium',
      addRecord: 'Add Record',
    },
    weightTracking: {
      subtitle: 'Weight tracking',
      currentWeight: 'CURRENT WEIGHT',
      healthyReferencePrefix: 'Healthy reference',
      last90Days: 'Last 90 Days',
      smartInsights: 'Smart Insights',
      history: 'History',
      addEntry: 'Add entry',
      addWeightEntry: 'Add Weight Entry',
      weightPlaceholder: 'e.g. 5.3',
      enterValidWeight: 'Enter a valid weight in kg.',
      save: 'Save',
      current: 'Current',
      currentSuffix: 'vs current',
      withinHealthyRange: 'Within healthy range',
      belowHealthyRange: 'Below healthy range',
      aboveHealthyRange: 'Above healthy range',
      trendInRange: "{name}'s trend is currently aligned with the expected {target} range.",
      trendBelow: '{name} is tracking below the expected {target} range. A nutrition review can help.',
      trendAbove: '{name} is tracking above the expected {target} range. Portion and activity review is recommended.',
      referenceAwareTitle: 'Reference-aware trend',
      referenceAwareBody: 'Curve movement now compares directly against the healthy range band.',
      noDate: 'No date',
      petFallback: 'pet',
      todayFallback: 'Today',
      stableFallback: 'Stable',
      refs: {
        catBritish: 'Healthy range for British Shorthair is usually 3.2-7.7 kg.',
        catMaine: 'Healthy range for Maine Coon is usually 4.5-8.2 kg.',
        catRagdoll: 'Healthy range for Ragdoll is usually 3.6-9.0 kg.',
        catSiamese: 'Healthy range for Siamese is usually 2.5-5.5 kg.',
        catDefault: 'Typical healthy range for adult cats is usually 3.0-6.0 kg.',
        dogGolden: 'Healthy range for Golden Retriever is usually 25-34 kg.',
        dogLabrador: 'Healthy range for Labrador is usually 25-36 kg.',
        dogGerman: 'Healthy range for German Shepherd is usually 22-40 kg.',
        dogKangal: 'Healthy range for Kangal is usually 40-65 kg.',
        dogTerrier: 'Expected healthy Terrier range can vary by subtype, often around 6-12 kg.',
        dogDefault: 'General adult dog healthy range varies by breed; using a 10-30 kg reference for this profile.',
        default: 'A general reference range is used for this profile.',
      },
    },
    premium: {
      badge: 'V-Paw Premium',
      heading: 'Give your pet the\ncare they deserve',
      subheading: "Unlock the ultimate toolkit to manage\nyour pet's health, records, and daily life\nwith ease.",
      features: {
        unlimitedPetsTitle: 'Unlimited Pets',
        unlimitedPetsDesc: 'Add as many furry friends as you want.',
        fullHealthTitle: 'Full Health History',
        fullHealthDesc: 'Lifetime access to all medical records.',
        pdfPassportTitle: 'PDF Health Card',
        pdfPassportDesc: "Export your pet's complete health summary as a PDF.",
        aiTitle: 'AI Health Insights',
        aiDesc: "Smart analysis of your pet's health data.",
        remindersTitle: 'Smart Reminders',
        remindersDesc: 'Never miss a vaccination or pill again.',
      },
      table: {
        free: 'FREE',
        pro: 'PRO',
        petProfiles: 'Pet Profiles',
        healthRecords: 'Health Records',
        pdfExport: 'PDF Export',
        aiInsights: 'AI Insights',
        one: '1',
        unlimited: 'Unlimited',
        threeMonths: '3 months',
        lifetime: 'Lifetime',
      },
      upgrade: 'Upgrade for $4.99/mo',
      maybeLater: 'Maybe later',
    },
    profileEdit: {
      title: 'Edit Profile',
      nameLabel: 'Full Name',
      namePlaceholder: 'Full Name',
      avatarLabel: 'Avatar URL',
      avatarPlaceholder: 'https://...',
      save: 'Save',
      saving: 'Saving...',
      saveFailedTitle: 'Save failed',
      saveFailedBody: 'Profile could not be saved. Please try again.',
    },
  },
  tr: {
    vaccinations: {
      title: 'A��lar',
      needsAttention: 'Dikkat\nGerekiyor',
      needsAttentionBody: 'Hayvan�n�z�n tam korumada\noldu�undan ve sa�l�kl�\nkald���ndan emin olal�m.',
      oneOverdue: '1 Gecikmi�',
      oneDueSoon: '1 Yakla��yor',
      resolve: '��z',
      nextUp: 'SIRADAK�',
      vaccineHistory: 'A�I GE�M���',
      dueDate: 'Son Tarih',
      addVaccination: 'A�� Ekle',
      statuses: {
        overdue: 'Gecikmi�',
        dueSoon: 'Yakla��yor',
        upToDate: 'G�ncel',
      },
      nextCard: {
        name: 'Kuduz',
        subtitle: '1 y�ll�k a��',
        date: '12 Nis',
        inWeeks: '3 hafta sonra',
      },
      history: {
        bordetellaSub: 'Kennel �ks�r���',
        rabiesSub: '1 y�ll�k a��',
        dhppSub: 'Distemper, Parvo vb.',
        leptoSub: 'Bakteriyel enfeksiyon',
        bordetellaDate: '20 �ub 2026',
        rabiesDate: '12 Nis 2026',
        dhppDate: '15 Oca 2027',
        leptoDate: '10 Mar 2027',
      },
    },
    vetVisits: {
      title: 'Veteriner Ziyaretleri',
      medicalHistory: 'T�bbi Ge�mi�',
      visitsCount: '3 Ziyaret',
      totalCost: '$265 Toplam',
      addVisit: 'Ziyaret Ekle',
      addPayment: '�deme\nekle',
      attachDocuments: '+ Belge veya foto�raf ekle',
      visits: {
        v1Date: '5 Mar 2026',
        v1Title: 'Y�ll�k Kontrol\nve A��lar',
        v1Clinic: 'Downtown Vet Clinic',
        v1Doctor: 'Dr. Sarah Jenkins',
        v2Date: '12 Eki 2025',
        v2Title: 'Kulak Enfeksiyonu Kontrol�',
        v2Clinic: 'Downtown Vet Clinic',
        v2Doctor: 'Dr. Sarah Jenkins',
        v3Date: '10 Mar 2025',
        v3Title: 'Y�ll�k Kontrol',
        v3Clinic: 'City Pet Hospital',
        v3Doctor: 'Dr. Emily Chen',
      },
    },
    healthRecords: {
      title: 'Sa�l�k Kay�tlar�',
      overview: 'Sa�l�k �zeti',
      recordsCount: '6 Kay�t',
      activeCount: '2 Aktif',
      upToDate: 'G�ncel',
      allergies: 'Alerjiler',
      diagnoses: 'Tan�lar',
      labResults: 'Lab Sonu�lar�',
      activeSection: 'AKT�F',
      historySection: 'GE�M��',
      activeTitle: 'Tavuk Proteini',
      activeDate: '12 Eki 2025',
      activeBody: 'T�ketildi�inde �iddetli ka��nt�\nve pati �s�rma g�r�l�r.',
      activeBadge: 'Aktif',
      activeSeverity: 'Y�ksek',
      historyTitle: 'Pire Is�r�klar�',
      historyDate: '05 Haz 2024',
      historyBody: 'Mevsimsel koruyucu ile tedavi edildi.',
      resolvedBadge: '��z�ld�',
      historySeverity: 'Orta',
      addRecord: 'Kay�t Ekle',
    },
    weightTracking: {
      subtitle: 'Kilo takibi',
      currentWeight: 'G�NCEL K�LO',
      healthyReferencePrefix: 'Sa�l�kl� referans',
      last90Days: 'Son 90 G�n',
      smartInsights: 'Ak�ll� ��g�r�ler',
      history: 'Ge�mi�',
      addEntry: 'Kay�t ekle',
      addWeightEntry: 'Kilo Kayd� Ekle',
      weightPlaceholder: '�rn. 5,3',
      enterValidWeight: 'L�tfen kg cinsinden ge�erli bir de�er girin.',
      save: 'Kaydet',
      current: 'G�ncel',
      currentSuffix: 'g�ncele g�re',
      withinHealthyRange: 'Sa�l�kl� aral�kta',
      belowHealthyRange: 'Sa�l�kl� aral���n alt�nda',
      aboveHealthyRange: 'Sa�l�kl� aral���n �st�nde',
      trendInRange: '{name} i�in e�ilim �u an beklenen {target} aral���yla uyumlu.',
      trendBelow: '{name}, beklenen {target} aral���n�n alt�nda seyrediyor. Beslenme de�erlendirmesi yard�mc� olabilir.',
      trendAbove: '{name}, beklenen {target} aral���n�n �st�nde seyrediyor. Porsiyon ve aktivite d�zeni �nerilir.',
      referenceAwareTitle: 'Referans uyumlu e�ilim',
      referenceAwareBody: 'E�ri hareketi art�k sa�l�kl� aral�k band�yla do�rudan kar��la�t�r�l�r.',
      noDate: 'Tarih yok',
      petFallback: 'hayvan',
      todayFallback: 'Bug�n',
      stableFallback: 'Stabil',
      refs: {
        catBritish: 'British Shorthair i�in sa�l�kl� aral�k genelde 3.2-7.7 kg.',
        catMaine: 'Maine Coon i�in sa�l�kl� aral�k genelde 4.5-8.2 kg.',
        catRagdoll: 'Ragdoll i�in sa�l�kl� aral�k genelde 3.6-9.0 kg.',
        catSiamese: 'Siamese i�in sa�l�kl� aral�k genelde 2.5-5.5 kg.',
        catDefault: 'Yeti�kin kedilerde sa�l�kl� aral�k �o�unlukla 3.0-6.0 kg aras�d�r.',
        dogGolden: 'Golden Retriever i�in sa�l�kl� aral�k genelde 25-34 kg.',
        dogLabrador: 'Labrador i�in sa�l�kl� aral�k genelde 25-36 kg.',
        dogGerman: 'German Shepherd i�in sa�l�kl� aral�k genelde 22-40 kg.',
        dogKangal: 'Kangal i�in sa�l�kl� aral�k genelde 40-65 kg.',
        dogTerrier: 'Sa�l�kl� Terrier aral��� alt tipe g�re de�i�ebilir, genelde 6-12 kg band�ndad�r.',
        dogDefault: 'Yeti�kin k�peklerde sa�l�kl� aral�k �rka g�re de�i�ir; bu profil i�in 10-30 kg referans� kullan�l�yor.',
        default: 'Bu profil i�in genel bir referans aral��� kullan�l�yor.',
      },
    },
    premium: {
      badge: 'V-Paw Premium',
      heading: 'Hayvan�n�za hak etti�i\nbak�m� sunun',
      subheading: 'Hayvan�n�z�n sa�l�k, kay�t ve g�nl�k\nya�am y�netimi i�in t�m �zellikleri\ntek yerde a��n.',
      features: {
        unlimitedPetsTitle: 'S�n�rs�z Hayvan',
        unlimitedPetsDesc: 'Diledi�iniz kadar dost ekleyin.',
        fullHealthTitle: 'Tam Sa�l�k Ge�mi�i',
        fullHealthDesc: 'T�m t�bbi kay�tlara �m�r boyu eri�im.',
        pdfPassportTitle: 'PDF Sağlık Kartı',
        pdfPassportDesc: 'Hayvanınızın sağlık özetini PDF olarak dışa aktarın.',
        aiTitle: 'Yapay Zeka ��g�r�leri',
        aiDesc: 'Hayvan�n�z�n sa�l�k verilerine ak�ll� analiz.',
        remindersTitle: 'Ak�ll� Hat�rlatmalar',
        remindersDesc: 'A�� veya ila� takibini ka��rmay�n.',
      },
      table: {
        free: '�CRETS�Z',
        pro: 'PRO',
        petProfiles: 'Hayvan Profilleri',
        healthRecords: 'Sa�l�k Kay�tlar�',
        pdfExport: 'PDF D��a Aktar�m',
        aiInsights: 'YZ ��g�r�leri',
        one: '1',
        unlimited: 'S�n�rs�z',
        threeMonths: '3 ay',
        lifetime: '�m�r boyu',
      },
      upgrade: 'Ayl�k $4.99 ile y�kselt',
      maybeLater: 'Daha sonra',
    },
    profileEdit: {
      title: 'Profili D�zenle',
      nameLabel: 'Ad Soyad',
      namePlaceholder: 'Ad Soyad',
      avatarLabel: 'Avatar URL',
      avatarPlaceholder: 'https://...',
      save: 'Kaydet',
      saving: 'Kaydediliyor...',
      saveFailedTitle: 'Kaydetme ba�ar�s�z',
      saveFailedBody: 'Profil kaydedilemedi. L�tfen tekrar deneyin.',
    },
  },
} as const;

export function getWording(locale: Locale) {
  return wording[locale] ?? wording.en;
}

