import type { Locale } from '../hooks/useLocale';

export const wording = {
  en: {
    vaccinations: {
      title: 'Vaccinations',
      needsAttention: 'Needs\nAttention',
      needsAttentionBody: "Let's ensure your pet\nstays fully protected and\nhealthy.",
      oneOverdue: '1 Overdue',
      oneDueSoon: '1 Due soon',
      resolve: 'Resolve',
      nextUp: 'NEXT UP',
      vaccineHistory: 'VACCINE HISTORY',
      dueDate: 'Due Date',
      addVaccination: 'Add Vaccination',
      statuses: {
        overdue: 'Overdue',
        dueSoon: 'Due soon',
        upToDate: 'Up to date',
      },
      nextCard: {
        name: 'Rabies',
        subtitle: '1-year vaccine',
        date: 'Apr 12',
        inWeeks: 'in 3 weeks',
      },
      history: {
        bordetellaSub: 'Kennel Cough',
        rabiesSub: '1-year vaccine',
        dhppSub: 'Distemper, Parvo, etc.',
        leptoSub: 'Bacterial infection',
        bordetellaDate: 'Feb 20, 2026',
        rabiesDate: 'Apr 12, 2026',
        dhppDate: 'Jan 15, 2027',
        leptoDate: 'Mar 10, 2027',
      },
    },
    vetVisits: {
      title: 'Vet Visits',
      medicalHistory: 'Medical History',
      visitsCount: '3 Visits',
      totalCost: '$265 Total',
      addVisit: 'Add Visit',
      addPayment: 'Add\npayment',
      attachDocuments: '+ Attach documents or photos',
      visits: {
        v1Date: 'Mar 5, 2026',
        v1Title: 'Annual Checkup\n& Vaccines',
        v1Clinic: 'Downtown Vet Clinic',
        v1Doctor: 'Dr. Sarah Jenkins',
        v2Date: 'Oct 12, 2025',
        v2Title: 'Ear Infection Follow-up',
        v2Clinic: 'Downtown Vet Clinic',
        v2Doctor: 'Dr. Sarah Jenkins',
        v3Date: 'Mar 10, 2025',
        v3Title: 'Annual Checkup',
        v3Clinic: 'City Pet Hospital',
        v3Doctor: 'Dr. Emily Chen',
      },
    },
    healthRecords: {
      title: 'Health Records',
      overview: 'Health Overview',
      recordsCount: '6 Records',
      activeCount: '2 Active',
      upToDate: 'Up to date',
      allergies: 'Allergies',
      diagnoses: 'Diagnoses',
      labResults: 'Lab Results',
      activeSection: 'ACTIVE',
      historySection: 'HISTORY',
      activeTitle: 'Chicken Protein',
      activeDate: 'Oct 12, 2025',
      activeBody: 'Severe itching and paw biting\nwhen consumed.',
      activeBadge: 'Active',
      activeSeverity: 'High',
      historyTitle: 'Flea Bites',
      historyDate: 'Jun 05, 2024',
      historyBody: 'Treated with seasonal preventative.',
      resolvedBadge: 'Resolved',
      historySeverity: 'Medium',
      addRecord: 'Add Record',
    },
    weightTracking: {
      subtitle: 'Weight tracking',
      currentWeight: 'CURRENT WEIGHT',
      healthyReferencePrefix: 'Healthy reference',
      last90Days: 'Last 90 Days',
      smartInsights: 'Smart Insights',
      history: 'History',
      addEntry: 'Add entry',
      addWeightEntry: 'Add Weight Entry',
      weightPlaceholder: 'e.g. 5.3',
      enterValidWeight: 'Enter a valid weight in kg.',
      save: 'Save',
      current: 'Current',
      currentSuffix: 'vs current',
      withinHealthyRange: 'Within healthy range',
      belowHealthyRange: 'Below healthy range',
      aboveHealthyRange: 'Above healthy range',
      trendInRange: "{name}'s trend is currently aligned with the expected {target} range.",
      trendBelow: '{name} is tracking below the expected {target} range. A nutrition review can help.',
      trendAbove: '{name} is tracking above the expected {target} range. Portion and activity review is recommended.',
      referenceAwareTitle: 'Reference-aware trend',
      referenceAwareBody: 'Curve movement now compares directly against the healthy range band.',
      noDate: 'No date',
      petFallback: 'pet',
      todayFallback: 'Today',
      stableFallback: 'Stable',
      refs: {
        catBritish: 'Healthy range for British Shorthair is usually 3.2-7.7 kg.',
        catMaine: 'Healthy range for Maine Coon is usually 4.5-8.2 kg.',
        catRagdoll: 'Healthy range for Ragdoll is usually 3.6-9.0 kg.',
        catSiamese: 'Healthy range for Siamese is usually 2.5-5.5 kg.',
        catDefault: 'Typical healthy range for adult cats is usually 3.0-6.0 kg.',
        dogGolden: 'Healthy range for Golden Retriever is usually 25-34 kg.',
        dogLabrador: 'Healthy range for Labrador is usually 25-36 kg.',
        dogGerman: 'Healthy range for German Shepherd is usually 22-40 kg.',
        dogKangal: 'Healthy range for Kangal is usually 40-65 kg.',
        dogTerrier: 'Expected healthy Terrier range can vary by subtype, often around 6-12 kg.',
        dogDefault: 'General adult dog healthy range varies by breed; using a 10-30 kg reference for this profile.',
        default: 'A general reference range is used for this profile.',
      },
    },
    premium: {
      badge: 'V-Paw Premium',
      heading: 'Give your pet the\ncare they deserve',
      subheading: "Unlock the ultimate toolkit to manage\nyour pet's health, records, and daily life\nwith ease.",
      features: {
        unlimitedPetsTitle: 'Unlimited Pets',
        unlimitedPetsDesc: 'Add as many furry friends as you want.',
        fullHealthTitle: 'Full Health History',
        fullHealthDesc: 'Lifetime access to all medical records.',
        pdfPassportTitle: 'PDF Passport Export',
        pdfPassportDesc: 'Generate official documents for travel.',
        aiTitle: 'AI Health Insights',
        aiDesc: "Smart analysis of your pet's health data.",
        remindersTitle: 'Smart Reminders',
        remindersDesc: 'Never miss a vaccination or pill again.',
      },
      table: {
        free: 'FREE',
        pro: 'PRO',
        petProfiles: 'Pet Profiles',
        healthRecords: 'Health Records',
        pdfExport: 'PDF Export',
        aiInsights: 'AI Insights',
        one: '1',
        unlimited: 'Unlimited',
        threeMonths: '3 months',
        lifetime: 'Lifetime',
      },
      upgrade: 'Upgrade for $4.99/mo',
      maybeLater: 'Maybe later',
    },
    profileEdit: {
      title: 'Edit Profile',
      nameLabel: 'Full Name',
      namePlaceholder: 'Full Name',
      avatarLabel: 'Avatar URL',
      avatarPlaceholder: 'https://...',
      save: 'Save',
      saving: 'Saving...',
      saveFailedTitle: 'Save failed',
      saveFailedBody: 'Profile could not be saved. Please try again.',
    },
  },
  tr: {
    vaccinations: {
      title: 'Aþýlar',
      needsAttention: 'Dikkat\nGerekiyor',
      needsAttentionBody: 'Hayvanýnýzýn tam korumada\nolduðundan ve saðlýklý\nkaldýðýndan emin olalým.',
      oneOverdue: '1 Gecikmiþ',
      oneDueSoon: '1 Yaklaþýyor',
      resolve: 'Çöz',
      nextUp: 'SIRADAKÝ',
      vaccineHistory: 'AÞI GEÇMÝÞÝ',
      dueDate: 'Son Tarih',
      addVaccination: 'Aþý Ekle',
      statuses: {
        overdue: 'Gecikmiþ',
        dueSoon: 'Yaklaþýyor',
        upToDate: 'Güncel',
      },
      nextCard: {
        name: 'Kuduz',
        subtitle: '1 yýllýk aþý',
        date: '12 Nis',
        inWeeks: '3 hafta sonra',
      },
      history: {
        bordetellaSub: 'Kennel Öksürüðü',
        rabiesSub: '1 yýllýk aþý',
        dhppSub: 'Distemper, Parvo vb.',
        leptoSub: 'Bakteriyel enfeksiyon',
        bordetellaDate: '20 Þub 2026',
        rabiesDate: '12 Nis 2026',
        dhppDate: '15 Oca 2027',
        leptoDate: '10 Mar 2027',
      },
    },
    vetVisits: {
      title: 'Veteriner Ziyaretleri',
      medicalHistory: 'Týbbi Geçmiþ',
      visitsCount: '3 Ziyaret',
      totalCost: '$265 Toplam',
      addVisit: 'Ziyaret Ekle',
      addPayment: 'Ödeme\nekle',
      attachDocuments: '+ Belge veya fotoðraf ekle',
      visits: {
        v1Date: '5 Mar 2026',
        v1Title: 'Yýllýk Kontrol\nve Aþýlar',
        v1Clinic: 'Downtown Vet Clinic',
        v1Doctor: 'Dr. Sarah Jenkins',
        v2Date: '12 Eki 2025',
        v2Title: 'Kulak Enfeksiyonu Kontrolü',
        v2Clinic: 'Downtown Vet Clinic',
        v2Doctor: 'Dr. Sarah Jenkins',
        v3Date: '10 Mar 2025',
        v3Title: 'Yýllýk Kontrol',
        v3Clinic: 'City Pet Hospital',
        v3Doctor: 'Dr. Emily Chen',
      },
    },
    healthRecords: {
      title: 'Saðlýk Kayýtlarý',
      overview: 'Saðlýk Özeti',
      recordsCount: '6 Kayýt',
      activeCount: '2 Aktif',
      upToDate: 'Güncel',
      allergies: 'Alerjiler',
      diagnoses: 'Tanýlar',
      labResults: 'Lab Sonuçlarý',
      activeSection: 'AKTÝF',
      historySection: 'GEÇMÝÞ',
      activeTitle: 'Tavuk Proteini',
      activeDate: '12 Eki 2025',
      activeBody: 'Tüketildiðinde þiddetli kaþýntý\nve pati ýsýrma görülür.',
      activeBadge: 'Aktif',
      activeSeverity: 'Yüksek',
      historyTitle: 'Pire Isýrýklarý',
      historyDate: '05 Haz 2024',
      historyBody: 'Mevsimsel koruyucu ile tedavi edildi.',
      resolvedBadge: 'Çözüldü',
      historySeverity: 'Orta',
      addRecord: 'Kayýt Ekle',
    },
    weightTracking: {
      subtitle: 'Kilo takibi',
      currentWeight: 'GÜNCEL KÝLO',
      healthyReferencePrefix: 'Saðlýklý referans',
      last90Days: 'Son 90 Gün',
      smartInsights: 'Akýllý Ýçgörüler',
      history: 'Geçmiþ',
      addEntry: 'Kayýt ekle',
      addWeightEntry: 'Kilo Kaydý Ekle',
      weightPlaceholder: 'örn. 5,3',
      enterValidWeight: 'Lütfen kg cinsinden geçerli bir deðer girin.',
      save: 'Kaydet',
      current: 'Güncel',
      currentSuffix: 'güncele göre',
      withinHealthyRange: 'Saðlýklý aralýkta',
      belowHealthyRange: 'Saðlýklý aralýðýn altýnda',
      aboveHealthyRange: 'Saðlýklý aralýðýn üstünde',
      trendInRange: '{name} için eðilim þu an beklenen {target} aralýðýyla uyumlu.',
      trendBelow: '{name}, beklenen {target} aralýðýnýn altýnda seyrediyor. Beslenme deðerlendirmesi yardýmcý olabilir.',
      trendAbove: '{name}, beklenen {target} aralýðýnýn üstünde seyrediyor. Porsiyon ve aktivite düzeni önerilir.',
      referenceAwareTitle: 'Referans uyumlu eðilim',
      referenceAwareBody: 'Eðri hareketi artýk saðlýklý aralýk bandýyla doðrudan karþýlaþtýrýlýr.',
      noDate: 'Tarih yok',
      petFallback: 'hayvan',
      todayFallback: 'Bugün',
      stableFallback: 'Stabil',
      refs: {
        catBritish: 'British Shorthair için saðlýklý aralýk genelde 3.2-7.7 kg.',
        catMaine: 'Maine Coon için saðlýklý aralýk genelde 4.5-8.2 kg.',
        catRagdoll: 'Ragdoll için saðlýklý aralýk genelde 3.6-9.0 kg.',
        catSiamese: 'Siamese için saðlýklý aralýk genelde 2.5-5.5 kg.',
        catDefault: 'Yetiþkin kedilerde saðlýklý aralýk çoðunlukla 3.0-6.0 kg arasýdýr.',
        dogGolden: 'Golden Retriever için saðlýklý aralýk genelde 25-34 kg.',
        dogLabrador: 'Labrador için saðlýklý aralýk genelde 25-36 kg.',
        dogGerman: 'German Shepherd için saðlýklý aralýk genelde 22-40 kg.',
        dogKangal: 'Kangal için saðlýklý aralýk genelde 40-65 kg.',
        dogTerrier: 'Saðlýklý Terrier aralýðý alt tipe göre deðiþebilir, genelde 6-12 kg bandýndadýr.',
        dogDefault: 'Yetiþkin köpeklerde saðlýklý aralýk ýrka göre deðiþir; bu profil için 10-30 kg referansý kullanýlýyor.',
        default: 'Bu profil için genel bir referans aralýðý kullanýlýyor.',
      },
    },
    premium: {
      badge: 'V-Paw Premium',
      heading: 'Hayvanýnýza hak ettiði\nbakýmý sunun',
      subheading: 'Hayvanýnýzýn saðlýk, kayýt ve günlük\nyaþam yönetimi için tüm özellikleri\ntek yerde açýn.',
      features: {
        unlimitedPetsTitle: 'Sýnýrsýz Hayvan',
        unlimitedPetsDesc: 'Dilediðiniz kadar dost ekleyin.',
        fullHealthTitle: 'Tam Saðlýk Geçmiþi',
        fullHealthDesc: 'Tüm týbbi kayýtlara ömür boyu eriþim.',
        pdfPassportTitle: 'PDF Pasaport Dýþa Aktarma',
        pdfPassportDesc: 'Seyahat için resmi belgeler oluþturun.',
        aiTitle: 'Yapay Zeka Ýçgörüleri',
        aiDesc: 'Hayvanýnýzýn saðlýk verilerine akýllý analiz.',
        remindersTitle: 'Akýllý Hatýrlatmalar',
        remindersDesc: 'Aþý veya ilaç takibini kaçýrmayýn.',
      },
      table: {
        free: 'ÜCRETSÝZ',
        pro: 'PRO',
        petProfiles: 'Hayvan Profilleri',
        healthRecords: 'Saðlýk Kayýtlarý',
        pdfExport: 'PDF Dýþa Aktarým',
        aiInsights: 'YZ Ýçgörüleri',
        one: '1',
        unlimited: 'Sýnýrsýz',
        threeMonths: '3 ay',
        lifetime: 'Ömür boyu',
      },
      upgrade: 'Aylýk $4.99 ile yükselt',
      maybeLater: 'Daha sonra',
    },
    profileEdit: {
      title: 'Profili Düzenle',
      nameLabel: 'Ad Soyad',
      namePlaceholder: 'Ad Soyad',
      avatarLabel: 'Avatar URL',
      avatarPlaceholder: 'https://...',
      save: 'Kaydet',
      saving: 'Kaydediliyor...',
      saveFailedTitle: 'Kaydetme baþarýsýz',
      saveFailedBody: 'Profil kaydedilemedi. Lütfen tekrar deneyin.',
    },
  },
} as const;

export function getWording(locale: Locale) {
  return wording[locale] ?? wording.en;
}

